<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/comparacoes_e_indexacao_booleana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np

##**Comparações e Indexação Booleana**

**Comparações:**

In [2]:
# criação dos arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([1.5, 3.5])
print("x: \n", x)
print("y: \n", y)

x: 
 [[1 2]
 [3 4]]
y: 
 [1.5 3.5]


In [3]:
# comparações ponto a ponto
print("Comparação de um array com um escalar (>): \n", x > 2)
print("Comparação de um array com um escalar (>=): \n", x >= 2)
print("Comparação de um array com um escalar (<): \n", x < 2)
print("Comparação de um array com um escalar (<=): \n", x <= 2)
print("Comparação entre arrays (==): \n", x == x)
print("Comparação entre arrays (>): \n", x > x)
print("Comparação entre arrays (>): \n", x > y) # broadcasting

Comparação de um array com um escalar (>): 
 [[False False]
 [ True  True]]
Comparação de um array com um escalar (>=): 
 [[False  True]
 [ True  True]]
Comparação de um array com um escalar (<): 
 [[ True False]
 [False False]]
Comparação de um array com um escalar (<=): 
 [[ True  True]
 [False False]]
Comparação entre arrays (==): 
 [[ True  True]
 [ True  True]]
Comparação entre arrays (>): 
 [[False False]
 [False False]]
Comparação entre arrays (>): 
 [[False False]
 [ True  True]]


**Indexação booleana:**

In [5]:
# indexação booleana (Operação de filtragem)
x = np.array([[1, 3, 7], 
             [4, 11, 21],
             [42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [7]:
# indexação booleana: retornar o número de elementos
# maiores que k
k = 10
cond = x > k
print("condição: \n", cond)
print(f"elementos maiores que {k}:", x[cond])
print(f"número de elementos maiores que {k}:", len(x[cond]))

condição: 
 [[False False False]
 [False  True  True]
 [ True False False]]
elementos maiores que 10: [11 21 42]
número de elementos maiores que 10: 3


In [8]:
# indexação booleana: extração dos números pares
cond = x % 2 == 0 # números pares
print("condição: \n", cond)
print("números pares: ", x[cond])

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
números pares:  [ 4 42  8]


In [9]:
# indexação booleana: extração dos números ímpares
cond = x % 2 == 1 # números ímpares
print("condição: \n", cond)
print("números pares: ", x[cond])

condição: 
 [[ True  True  True]
 [False  True  True]
 [False False  True]]
números pares:  [ 1  3  7 11 21  9]
