**Imports**

In [1]:
import numpy as np

**Criação de Arrays**

In [2]:
# criação de um array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("x:", x)
print("shape:", x.shape)

x: [1 2 3]
shape: (3,)


In [3]:
type(x)

numpy.ndarray

In [5]:
# criação de um array 2D: Listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1 2]
 [3 4]]
shape: (2, 2)


In [6]:
type(x)

numpy.ndarray

In [7]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [8]:
# array contendo apenas 0's
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[0. 0.]
 [0. 0.]]
shape: (2, 2)


In [10]:
# array contendo apenas 1's
size = (3, 3) # (linhas, colunas)
x = np.ones(size)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape: (3, 3)


In [11]:
# criação de valores dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print("x:", x)
print("shape:", x.shape)

x: [ 5.  7.  9. 11. 13. 15.]
shape: (6,)


In [12]:
# criação da matriz identidade
n = 4
x = np.eye(n)
print("x:\n", x)
print("shape:", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape: (4, 4)


In [13]:
# criação de valores aleatórios
# np.random.seed(10)
x = np.random.random(size=(2, 3))
print("x:\n", x)
print("shape:", x.shape)

x:
 [[0.38383522 0.11317296 0.53296367]
 [0.6643166  0.16480304 0.85493382]]
shape: (2, 3)
