<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/indexacao_de_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# imports
import numpy as np

**Indexação de arrays**

In [2]:
a = [88, 19, 46, 74, 94]

**Acessando um elemento pelo índice**

In [3]:
a[1]

19

**Acessando o último elemento do array**



In [4]:
a[4]

94

ou posso utilizar dessa outra forma:

In [5]:
a[-1]
a[-2]

74

**Slicing (Fatiamento)**

In [6]:
a[1:3]

[19, 46]

**Praticando a indexação de arrays**

In [10]:
# os índices no Python vão de 0 a n-1,
# onde n é o tamanho da dimensão
x = np.linspace(start=10, stop=100, num=10)
print("x:", x)
print("shape:", x.shape)

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [11]:
# extração de elementos
print("x:", x)
print("primeiro elemento:", x[0])
print("segundo elemento:", x[1])
print("último elemento:", x[9])
print("último elemento:", x[-1])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
segundo elemento: 20.0
último elemento: 100.0
último elemento: 100.0


In [12]:
# slicing: extração de subarrays:
print("x:", x)
print("dois primeiros elementos:", x[0:2])
print("dois primeiros elementos:", x[:2])
print("dois últimos elementos:", x[-2:])

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primeiros elementos: [10. 20.]
dois últimos elementos: [ 90. 100.]


In [13]:
# slicing em arrays 2D (Matrizes)
x = x.reshape(2, 5) # reshape de x para 2 linhas e 5 colunas
print("x:\n", x)

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [14]:
# extração de elementos
print("primeira linha, segunda coluna", x[0, 1])
print("segunda linha, penúltima coluna", x[1, -2])
print("última linha, última coluna", x[1, 4])
print("última linha, última coluna", x[-1, -1])

primeira linha, segunda coluna 20.0
segunda linha, penúltima coluna 90.0
última linha, última coluna 100.0
última linha, última coluna 100.0


In [15]:
# slicing: extração de subarrays
print("x:\n", x)
print("primeira linha inteira: ", x[0, :])
print("primeira linha, segunda a quarta coluna: ", x[0, 1:4])
print("última coluna inteira: ", x[:, [-1]])

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]
primeira linha inteira:  [10. 20. 30. 40. 50.]
primeira linha, segunda a quarta coluna:  [20. 30. 40.]
última coluna inteira:  [[ 50.]
 [100.]]


In [16]:
# atenção com o compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print("x antes: ", x)
y = x[:2]
y[0] = -100 # alteração do valor em y altera o valor de x
print("x depois: ", x)

x antes:  [1 2 3]
x depois:  [-100    2    3]


In [17]:
# atenção com o compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print("x antes: ", x)
y = x[:2].copy()
y[0] = -100 # alteração do valor em y altera o valor de x
print("x depois: ", x)

x antes:  [1 2 3]
x depois:  [1 2 3]
