<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np

##**Numpy**

In [2]:
# array
x = np.array([[1, 3, 7],
             [4, 11, 21],
              [42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [3]:
# reshape: transformar a matriz em um vetor coluna
# (3, 3) vira (9, 1): 3*3 = 9*1 = 9
print("transformação de em um vetor coluna: \n", x.reshape(9, 1))

transformação de em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [5]:
# transposição de matriz
print("x transposta: \n", x.T)

x transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [6]:
# np.sum: soma em um dado eixo, axis = {0: linha, 1: coluna}
print("x:\n", x)
print("soma de todos os elementos de x:", np.sum(x))
print("soma de x ao longo das linhas:", np.sum(x, axis=0))
print("soma de x ao longo das colunas:", np.sum(x, axis=1))

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
soma de todos os elementos de x: 106
soma de x ao longo das linhas: [47 22 37]
soma de x ao longo das colunas: [11 36 59]


In [7]:
# np.mean: média em um dado eixo, axis = {0: linha, 1: coluna}
print("x:\n", x)
print("média de todos os elementos de x:", np.mean(x))
print("média de x ao longo das linhas:", np.mean(x, axis=0))
print("média de x ao longo das colunas:", np.mean(x, axis=1))

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
média de todos os elementos de x: 11.777777777777779
média de x ao longo das linhas: [15.66666667  7.33333333 12.33333333]
média de x ao longo das colunas: [ 3.66666667 12.         19.66666667]


In [9]:
# np.where, identificação dos índices onde uma data condição
# é atendida. Uso conjunto com indexação booleana
cond = x % 2 == 0 # números pares
print("condição: \n", cond)
i, j = np.where(cond) # índices x[i, j] = x[cond]
print("índice i (linhas):", i)
print("índice j (linhas):", j)

condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
índice i (linhas): [1 2 2]
índice j (linhas): [0 0 1]


In [10]:
# indexação booleana e slicing: selecionar as linhas
# de x que possuem algum número par
print("x:\n", x)
cond = x % 2 == 0 # números pares
print("condição: \n", cond)

# se houver alguma condição True na linha, a soma será > 0
i_row = np.where(np.sum(cond, axis=1))[0]
print("índice das linhas que possuem números pares:", i_row)
print("linhas que possuem números pares: \n", x[i_row, :])


x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
condição: 
 [[False False False]
 [ True False False]
 [ True  True False]]
índice das linhas que possuem números pares: [1 2]
linhas que possuem números pares: 
 [[ 4 11 21]
 [42  8  9]]
