<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np

##**Numpy**

In [2]:
# array
x = np.array([[1, 3, 7],
             [4, 11, 21],
              [42, 8, 9]])
print("x:\n", x)

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]


In [3]:
# reshape: transformar a matriz em um vetor coluna
# (3, 3) vira (9, 1): 3*3 = 9*1 = 9
print("transformação de em um vetor coluna: \n", x.reshape(9, 1))

transformação de em um vetor coluna: 
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [11]
 [21]
 [42]
 [ 8]
 [ 9]]


In [5]:
# transposição de matriz
print("x transposta: \n", x.T)

x transposta: 
 [[ 1  4 42]
 [ 3 11  8]
 [ 7 21  9]]


In [6]:
# np.sum: soma em um dado eixo, axis = {0: linha, 1: coluna}
print("x:\n", x)
print("soma de todos os elementos de x:", np.sum(x))
print("soma de x ao longo das linhas:", np.sum(x, axis=0))
print("soma de x ao longo das colunas:", np.sum(x, axis=1))

x:
 [[ 1  3  7]
 [ 4 11 21]
 [42  8  9]]
soma de todos os elementos de x: 106
soma de x ao longo das linhas: [47 22 37]
soma de x ao longo das colunas: [11 36 59]
