<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/operacoes_com_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np

**Operações com arrays**

In [2]:
# criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [3]:
# soma
print("soma de dois arrays:\n", x + y)
print("soma com float/int:\n", x + 2) # broadcasting

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


In [4]:
# subtração
print("subtração de dois arrays:\n", x - y)
print("subtração com float/int:\n", x - 2) # broadcasting

subtração de dois arrays:
 [[0. 1.]
 [1. 0.]]
subtração com float/int:
 [[-1. -1.]
 [-1. -1.]]


In [5]:
# divisão
print("divisão de dois arrays:\n", x / y)
print("divisão com float/int:\n", x / 2) # broadcasting

divisão de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisão com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [6]:
# quando o broadcasting não funciona
np.array([1, 2, 3]) + np.array([1, 2])

ValueError: ignored

In [7]:
# soma, subtração e divisão
print("combinação de operações: \n", (x+y)/(x-2))

combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]


**Funções aritméticas: multiplicação**

In [8]:
# multiplicação elemento a elemento
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [9]:
# multiplicação
print("multiplicação de dois arrays:\n", x * y)
print("multiplicação com float/int:\n", x * 2) # broadcasting

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float/int:
 [[2. 2.]
 [2. 2.]]


In [10]:
# multiplicação matricial
print("multiplicação matricial (np.dot):\n", np.dot(x, y)) # função numpy
print("multiplicação matricial (@):\n", x @ y) # operador nativo python
print("multiplicação matricial (.dot):\n", x.dot(y)) # método .dot do objeto python

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]
multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


In [12]:
"""
Exemplo:
Solução d eum sistema de equações:
    a + 2*b = 7
  3*a + 2*b = -11  
  Solução análitica: (a, b) = (-1, 4)
Matricialmente, este problema tem a seguinte forma:
  Ax = c, onde:
  - x = [a, b]
  - A = [[1, 2], [3, -2]]
  - c = [7, -11]
  Solução numérica: xc = inv(A) @ c,
"""

# Definição do problema
A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print("A: \n", A)
print("c: \n", c)

A: 
 [[ 1  2]
 [ 3 -2]]
c: 
 [[  7]
 [-11]]


In [13]:
# solução
x = np.dot(np.linalg.inv(A), c)
x = np.linalg.inv(A) @ c
print("(a, b):", x.ravel())

(a, b): [-1.  4.]
