<a href="https://colab.research.google.com/github/wallaceleonardo/bootcamp-IGTI-Desenvolvedor_Python/blob/main/operacoes_com_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# imports
import numpy as np

**Operações com arrays**

In [2]:
# criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print("x: \n", x)
print("y: \n", y)

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [3]:
# soma
print("soma de dois arrays:\n", x + y)
print("soma com float/int:\n", x + 2) # broadcasting

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float/int:
 [[3. 3.]
 [3. 3.]]


In [4]:
# subtração
print("subtração de dois arrays:\n", x - y)
print("subtração com float/int:\n", x - 2) # broadcasting

subtração de dois arrays:
 [[0. 1.]
 [1. 0.]]
subtração com float/int:
 [[-1. -1.]
 [-1. -1.]]


In [5]:
# divisão
print("divisão de dois arrays:\n", x / y)
print("divisão com float/int:\n", x / 2) # broadcasting

divisão de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisão com float/int:
 [[0.5 0.5]
 [0.5 0.5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [6]:
# quando o broadcasting não funciona
np.array([1, 2, 3]) + np.array([1, 2])

ValueError: ignored

In [7]:
# soma, subtração e divisão
print("combinação de operações: \n", (x+y)/(x-2))

combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]
